# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Toske-Programer (Web Security Scanner contributors)
"""
PDF report generation for Pro plan.

Given a completed scan row (the JSONB blob from the scans table), this
module produces a branded multi-page PDF report. Used by the
GET /api/scan/{id}/pdf endpoint, which is gated on an active Pro
subscription.

Design notes:

- fpdf2 is chosen over weasyprint because weasyprint needs system libs
  (pango, cairo) that are not in the python:3.11-slim base image. fpdf2
  is pure Python and works with no extra install.

- fpdf2's built-in Helvetica font is latin1 only. Scanner check messages
  use Serbian Latin with diacritics (cscdz) which latin1 does not cover.
  We transliterate to diacritic-free ASCII before every draw call via
  _ascii(). The text stays readable ("izostavljanje" instead of
  "izostavljanje") and no TTF file has to be bundled.

- Every public helper returns a PDF as bytes, so the api.py endpoint
  can wrap it in a FileResponse or StreamingResponse without touching
  disk.
"""
from __future__ import annotations

import unicodedata
from datetime import datetime
from typing import Any, Dict, List, Optional

from fpdf import FPDF

# Page layout
PAGE_W = 210  # A4 width in mm
MARGIN_L = 15
MARGIN_R = 15
MARGIN_T = 20
CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R  # 180mm

# Brand colors (RGB tuples) — matched to the scanner's web UI
COLOR_BG = (10, 12, 21)
COLOR_ACCENT = (167, 139, 250)     # #a78bfa purple
COLOR_TEXT = (232, 234, 246)
COLOR_MUTED = (123, 131, 166)
COLOR_BORDER = (37, 42, 74)
COLOR_GREEN = (74, 222, 128)
COLOR_YELLOW = (234, 179, 8)
COLOR_ORANGE = (249, 115, 22)
COLOR_RED = (239, 68, 68)

SEVERITY_COLOR = {
    "CRITICAL": COLOR_RED,
    "HIGH": COLOR_ORANGE,
    "MEDIUM": COLOR_YELLOW,
    "LOW": (132, 204, 22),
    "INFO": (156, 163, 175),
}

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def _ascii(text: Any, max_len: Optional[int] = None) -> str:
    """
    Transliterate a string to ASCII so fpdf2's latin1 Helvetica can render it.

    Drops combining marks (diacritics): kosmicni -> kosmicni.
    Any still-unsupported character (emoji, Cyrillic) becomes '?'.
    If max_len is given, the result is truncated with an ellipsis.
    """
    if text is None:
        return ""
    s = str(text)
    # NFKD separates base chars from combining marks, then we filter the marks
    decomposed = unicodedata.normalize("NFKD", s)
    ascii_str = "".join(c for c in decomposed if not unicodedata.combining(c))
    # Replace anything still outside latin1 with '?'
    ascii_str = ascii_str.encode("latin-1", errors="replace").decode("latin-1")
    if max_len and len(ascii_str) > max_len:
        ascii_str = ascii_str[: max_len - 1] + "~"
    return ascii_str


class _ScanReport(FPDF):
    """FPDF subclass with auto-header on every new page and auto-footer."""

    def __init__(self, domain: str, scan_date: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.domain = _ascii(domain, 60)
        self.scan_date = _ascii(scan_date, 40)
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(MARGIN_L, MARGIN_T, MARGIN_R)
        self.set_creator("Web Security Scanner Pro")
        self.set_author("Web Security Scanner")
        self.set_title(f"Security Report for {self.domain}")

    def header(self):
        # Thin top bar with brand + domain on every page except the first
        # (the first page has its own hero block). Page 1 is drawn before
        # header() is called again, so the check compares page_no() > 1.
        if self.page_no() == 1:
            return
        self.set_y(8)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(0, 5, _ascii("Web Security Scanner"), 0, 0, "L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 5, self.domain, 0, 1, "R")
        # Thin accent rule
        self.set_draw_color(*COLOR_ACCENT)
        self.set_line_width(0.3)
        self.line(MARGIN_L, 16, PAGE_W - MARGIN_R, 16)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*COLOR_MUTED)
        left = _ascii("Generated by Web Security Scanner Pro")
        right = f"Page {self.page_no()}/{{nb}}"
        self.cell(0, 4, left, 0, 0, "L")
        self.cell(0, 4, right, 0, 1, "R")
        self.set_font("Helvetica", "", 6)
        self.cell(0, 3, _ascii(f"Report generated {self.scan_date}"), 0, 0, "L")
        self.cell(0, 3, _ascii("security-scanner-ruddy.vercel.app"), 0, 1, "R")


# ──────────────────────────────────────────────────────────────────────
# Section renderers
# ──────────────────────────────────────────────────────────────────────
def _draw_cover(pdf: _ScanReport, scan: Dict[str, Any]) -> None:
    """Draw the big branded cover block on page 1."""
    pdf.set_y(25)
    # Logo + brand
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*COLOR_ACCENT)
    pdf.cell(0, 10, _ascii("Web Security Scanner"), 0, 1, "L")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(0, 6, _ascii("Passive website security analysis"), 0, 1, "L")
    pdf.ln(8)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 10, _ascii("Security Report"), 0, 1, "L")
    pdf.ln(3)

    # Metadata block
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(40, 7, _ascii("Domain:"), 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 7, _ascii(scan.get("domain") or scan.get("url") or "unknown"), 0, 1)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(40, 7, _ascii("Scanned URL:"), 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 7, _ascii(scan.get("url") or "unknown", 90), 0, 1)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(40, 7, _ascii("Report date:"), 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 7, _ascii(pdf.scan_date), 0, 1)

    scan_time = scan.get("scan_time")
    if scan_time:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*COLOR_MUTED)
        pdf.cell(40, 7, _ascii("Scan duration:"), 0, 0)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*COLOR_TEXT)
        pdf.cell(0, 7, _ascii(f"{float(scan_time):.2f}s"), 0, 1)

    pdf.ln(10)


def _draw_score_card(pdf: _ScanReport, score_data: Dict[str, Any]) -> None:
    """Big grade + score card near the top of page 1."""
    if not score_data:
        return

    grade = score_data.get("grade", "?")
    score = score_data.get("score", 0)
    label = score_data.get("grade_label", "")

    # Background card
    card_y = pdf.get_y()
    pdf.set_fill_color(245, 245, 250)
    pdf.set_draw_color(*COLOR_BORDER)
    pdf.set_line_width(0.4)
    pdf.rect(MARGIN_L, card_y, CONTENT_W, 45, style="DF")

    # Grade letter (huge)
    pdf.set_xy(MARGIN_L + 10, card_y + 6)
    pdf.set_font("Helvetica", "B", 42)
    grade_color = _grade_color(grade)
    pdf.set_text_color(*grade_color)
    pdf.cell(30, 30, _ascii(grade), 0, 0, "C")

    # Score + label to the right of the grade
    pdf.set_xy(MARGIN_L + 50, card_y + 10)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 10, _ascii(f"Score: {score}/100"), 0, 1)

    pdf.set_x(MARGIN_L + 50)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, _ascii(label), 0, 1)

    # Counts row
    counts = score_data.get("counts") or {}
    pdf.set_xy(MARGIN_L + 50, card_y + 28)
    pdf.set_font("Helvetica", "", 9)
    counts_line = (
        f"CRITICAL: {counts.get('critical', 0)}   "
        f"HIGH: {counts.get('high', 0)}   "
        f"MEDIUM: {counts.get('medium', 0)}   "
        f"LOW: {counts.get('low', 0)}"
    )
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 5, _ascii(counts_line), 0, 1)

    pdf.set_y(card_y + 50)
    pdf.set_text_color(*COLOR_TEXT)


def _grade_color(grade: str) -> tuple:
    return {
        "A": (34, 197, 94),
        "B": (132, 204, 22),
        "C": (234, 179, 8),
        "D": (249, 115, 22),
        "F": (239, 68, 68),
    }.get(grade.upper(), (100, 100, 100))


def _draw_category_summary(pdf: _ScanReport, results: List[Dict[str, Any]]) -> None:
    """One-line-per-category pass/fail breakdown below the score card."""
    if not results:
        return
    by_category: Dict[str, Dict[str, int]] = {}
    for r in results:
        cat = r.get("category") or "Other"
        entry = by_category.setdefault(cat, {"passed": 0, "failed": 0})
        if r.get("passed"):
            entry["passed"] += 1
        else:
            entry["failed"] += 1

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, _ascii("Category summary"), 0, 1)
    pdf.ln(1)

    pdf.set_font("Helvetica", "", 10)
    for cat in sorted(by_category.keys()):
        entry = by_category[cat]
        line = f"{cat}: {entry['passed']} passed, {entry['failed']} failed"
        pdf.set_text_color(80, 80, 80)
        pdf.cell(5, 6, "-", 0, 0)
        pdf.cell(0, 6, _ascii(line), 0, 1)
    pdf.ln(4)


def _draw_findings(pdf: _ScanReport, results: List[Dict[str, Any]]) -> None:
    """Detailed findings list on subsequent pages."""
    if not results:
        return

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*COLOR_ACCENT)
    pdf.cell(0, 10, _ascii("Detailed findings"), 0, 1)
    pdf.ln(2)

    # Group by category, sort within category by severity then failed-first
    by_category: Dict[str, List[Dict[str, Any]]] = {}
    for r in results:
        by_category.setdefault(r.get("category") or "Other", []).append(r)

    sev_rank = {s: i for i, s in enumerate(SEVERITY_ORDER)}
    for cat in sorted(by_category.keys()):
        items = sorted(
            by_category[cat],
            key=lambda r: (
                0 if not r.get("passed") else 1,
                sev_rank.get(r.get("severity", "INFO"), 99),
                _ascii(r.get("name", "")),
            ),
        )

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(0, 7, _ascii(cat), 0, 1)
        pdf.set_draw_color(200, 200, 200)
        pdf.set_line_width(0.2)
        pdf.line(MARGIN_L, pdf.get_y(), PAGE_W - MARGIN_R, pdf.get_y())
        pdf.ln(2)

        for r in items:
            _draw_finding_row(pdf, r)
        pdf.ln(2)


def _draw_finding_row(pdf: _ScanReport, r: Dict[str, Any]) -> None:
    """Single finding block: colored severity chip + name + message."""
    passed = r.get("passed", False)
    sev = r.get("severity", "INFO")
    sev_color = SEVERITY_COLOR.get(sev, (120, 120, 120))
    name = _ascii(r.get("name") or r.get("check") or "(unnamed)", 70)
    message = _ascii(r.get("message") or r.get("details") or "", 220)

    # Status + severity chip
    status_text = "PASS" if passed else sev
    status_color = COLOR_GREEN if passed else sev_color

    y0 = pdf.get_y()
    # Left colored chip
    pdf.set_fill_color(*status_color)
    pdf.rect(MARGIN_L, y0 + 1, 3, 4, style="F")

    # Name (bold)
    pdf.set_xy(MARGIN_L + 5, y0)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 5, name, 0, 1)

    # Status label
    pdf.set_x(MARGIN_L + 5)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_text_color(*status_color)
    pdf.cell(0, 3, _ascii(f"[{status_text}]"), 0, 1)

    # Message (regular, wrapped)
    if message:
        pdf.set_x(MARGIN_L + 5)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(90, 90, 90)
        pdf.multi_cell(CONTENT_W - 5, 4, message, 0, "L")

    pdf.ln(1)


# ──────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────
def generate_pdf(scan_row: Dict[str, Any]) -> bytes:
    """
    Build a PDF report for one completed scan.

    scan_row is the full DB row from the scans table (or an equivalent
    in-memory dict with the same keys). The scan result payload lives
    under scan_row['result'] as produced by scanner.py.

    Returns the PDF content as bytes, ready to be sent in an
    HTTP response.
    """
    result = scan_row.get("result") or {}
    # scan_row itself carries url/domain at the top level; the nested
    # result may also carry them (scanner.py writes both). Prefer the
    # row-level values because they are what the user originally requested.
    url = scan_row.get("url") or result.get("url") or "unknown"
    domain = scan_row.get("domain") or result.get("domain") or "unknown"

    # Timestamp — prefer completed_at, fall back to created_at, else now
    ts = scan_row.get("completed_at") or scan_row.get("created_at")
    if ts:
        try:
            ts_dt = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
            scan_date = ts_dt.strftime("%Y-%m-%d %H:%M UTC")
        except (ValueError, TypeError):
            scan_date = str(ts)
    else:
        scan_date = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    pdf = _ScanReport(domain=domain, scan_date=scan_date)
    pdf.alias_nb_pages()  # enables {nb} placeholder in footer
    pdf.add_page()

    _draw_cover(pdf, {
        "domain": domain,
        "url": url,
        "scan_time": result.get("scan_time"),
    })
    _draw_score_card(pdf, result.get("score") or {})
    _draw_category_summary(pdf, result.get("results") or [])
    _draw_findings(pdf, result.get("results") or [])

    # fpdf2 returns bytes in recent versions; in older it returns str.
    # Coerce to bytes uniformly.
    output = pdf.output()
    if isinstance(output, (bytes, bytearray)):
        return bytes(output)
    return output.encode("latin-1")
