// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Toske-Programer (Web Security Scanner contributors)
// ============================================================================
// db_export.ts — SELECT critical tables and serialize as a backup payload
// ============================================================================
// We don't back up everything in the DB. Only tables whose loss would hurt:
//
//   - audit_log:         forensic / legal shield. Loss = legal exposure.
//   - abuse_reports:     user complaints / takedown evidence.
//   - scans:             historical scan records. Nice to have.
//   - verified_domains:  30-day verification cache. Saves re-verify friction.
//
// We explicitly DO NOT back up:
//
//   - verification_tokens: <1h TTL, ephemeral
//   - rate_limits:         ephemeral counters
//   - schema_migrations:   regenerated by re-running /migrations from disk
//   - backup_log:          don't back up the backup log itself (self-ref loop)
//
// The output is a single JSON object. On restore, we iterate the tables in
// the order listed here and INSERT rows. FK constraints: we have none
// between these tables right now, so order doesn't matter — but if/when
// we add them, this order is already topologically safe.
// ============================================================================

import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

const TABLES_TO_BACKUP = [
  "audit_log",
  "abuse_reports",
  "scans",
  "verified_domains",
] as const;

type TableName = typeof TABLES_TO_BACKUP[number];

export interface BackupPayload {
  schema_version: number;
  exported_at: string;          // ISO 8601
  trigger_source: string;
  row_counts: Record<TableName, number>;
  tables: Record<TableName, unknown[]>;
}

/**
 * Builds a Supabase client using the service_role key auto-injected into
 * edge functions by the Supabase runtime. service_role bypasses RLS, so
 * we can SELECT from any table including the append-only audit_log.
 */
export function makeServiceClient(): SupabaseClient {
  const url = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !serviceKey) {
    throw new Error(
      "SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in edge function env",
    );
  }
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

/**
 * Pages through a table 1000 rows at a time to avoid memory spikes if a
 * table ever grows to millions of rows. Returns the full row list.
 *
 * We order by primary key implicitly via the natural insertion order. For
 * our tables, id / BIGSERIAL ordering matches insertion time closely.
 */
async function fetchAllRows(
  client: SupabaseClient,
  table: TableName,
): Promise<unknown[]> {
  const PAGE_SIZE = 1000;
  const allRows: unknown[] = [];
  let offset = 0;

  while (true) {
    const { data, error } = await client
      .from(table)
      .select("*")
      .range(offset, offset + PAGE_SIZE - 1);

    if (error) {
      throw new Error(`fetch ${table} failed at offset ${offset}: ${error.message}`);
    }
    if (!data || data.length === 0) break;

    allRows.push(...data);
    if (data.length < PAGE_SIZE) break; // last page
    offset += PAGE_SIZE;
  }

  return allRows;
}

/**
 * Fetches all backup-critical tables and builds the payload object.
 * Tables are fetched sequentially rather than in parallel to keep
 * memory usage predictable on the edge function runtime.
 */
export async function buildBackupPayload(
  client: SupabaseClient,
  triggerSource: string,
): Promise<BackupPayload> {
  const tables: Record<string, unknown[]> = {};
  const rowCounts: Record<string, number> = {};

  for (const table of TABLES_TO_BACKUP) {
    const rows = await fetchAllRows(client, table);
    tables[table] = rows;
    rowCounts[table] = rows.length;
  }

  return {
    schema_version: 1, // bump when the on-disk format changes
    exported_at: new Date().toISOString(),
    trigger_source: triggerSource,
    row_counts: rowCounts as Record<TableName, number>,
    tables: tables as Record<TableName, unknown[]>,
  };
}

/**
 * Builds an R2 object key with date-partitioned structure so listing by
 * month/day is cheap in the R2 dashboard.
 *
 * Example:
 *   backups/2026/04/10/backup-20260410T040012Z.json.gz.enc
 */
export function buildObjectKey(triggerSource: string): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(now.getUTCDate()).padStart(2, "0");
  const stamp = now.toISOString().replace(/[:-]|\.\d{3}/g, ""); // 20260410T040012Z
  const suffix = triggerSource === "cron" ? "" : `-${triggerSource}`;
  return `backups/${yyyy}/${mm}/${dd}/backup-${stamp}${suffix}.json.gz.enc`;
}
