-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Toske-Programer (Web Security Scanner contributors)
-- Migration 017: Add fingerprint_hash to verified_domains
--
-- Problem: users with dynamic IPs (most home connections) lose their
-- 30-day verification when the router restarts and assigns a new IP.
-- Solution: store browser fingerprint alongside IP hash. Verification
-- is valid if EITHER ip_hash OR fingerprint_hash matches.
--
-- The UNIQUE constraint changes from (domain, ip_hash) to allow
-- multiple rows per domain (one per IP, one per fingerprint, or both).
-- We drop the old unique and add a new one on (domain, ip_hash, fingerprint_hash).

ALTER TABLE verified_domains
  ADD COLUMN IF NOT EXISTS fingerprint_hash TEXT;

-- Drop old unique constraint and create new one that includes fingerprint
-- The old constraint name was auto-generated by Supabase as
-- "verified_domains_domain_ip_hash_key"
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'verified_domains_domain_ip_hash_key'
  ) THEN
    ALTER TABLE verified_domains
      DROP CONSTRAINT verified_domains_domain_ip_hash_key;
  END IF;
END $$;

-- New unique: one verification per (domain, ip_hash) combination
-- fingerprint_hash can be NULL (legacy rows) or filled
CREATE UNIQUE INDEX IF NOT EXISTS verified_domains_domain_ip_key
  ON verified_domains (domain, ip_hash);

-- Index for fingerprint-based lookup (when IP changed but fingerprint same)
CREATE INDEX IF NOT EXISTS idx_verified_domains_fingerprint
  ON verified_domains (domain, fingerprint_hash)
  WHERE fingerprint_hash IS NOT NULL;
