-- =====================================================================
-- DR DRILL BOOTSTRAP SCRIPT
-- =====================================================================
-- Generated by concatenating migrations/001-010 in order.
-- Paste this entire file into the SQL Editor of a FRESH Supabase project
-- and click Run. It will rebuild the full scanner schema end-to-end.
--
-- Expected result: 10 migrations applied, 7 tables created, cron jobs
-- scheduled (harmless on staging until we delete the project).
--
-- This file is safe to commit to git — contains no secrets. The staging
-- project gets credentials only in the operators local notepad.
-- =====================================================================


-- =====================================================================
-- === 001_schema_migrations_table.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 001 — schema_migrations tracking table
-- ============================================================================
-- This is always the first migration. It creates the table that the
-- migration runner uses to track which migrations have already been
-- applied, so we can safely re-run `migrate.py` and skip completed work.
--
-- Never edit this file after it's been applied. If you need to change
-- something about how migrations work, add a NEW migration file.
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     TEXT PRIMARY KEY,           -- filename without .sql, e.g. "001_schema_migrations_table"
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checksum    TEXT NOT NULL,              -- sha256 of the file content at apply time
    runtime_ms  INTEGER                     -- how long the migration took, for diagnostics
);

COMMENT ON TABLE schema_migrations IS
    'Tracks applied database migrations. Managed by migration_runner.py. Never UPDATE or DELETE rows manually.';

-- =====================================================================
-- === 002_core_tables.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 002 — core tables for Function 6
-- ============================================================================
-- Tables:
--   scans                   — scan results (replaces in-memory dict)
--   verification_tokens     — short-lived ownership verification tokens
--   verified_domains        — 30-day cache of verified (domain, ip_hash) pairs
--   audit_log               — append-only forensic trail
--   rate_limits             — persistent rate-limit counters
--   abuse_reports           — user-submitted abuse reports
--
-- All tables follow these rules:
--   * Primary keys use TEXT/UUID, not sequential ints (ids are not guessable)
--   * All timestamps are TIMESTAMPTZ (never naive)
--   * PII is stored as HASH, never raw (ip_hash, ua_hash)
--   * JSONB for flexible fields (scan results, audit details)
--   * NOT NULL wherever possible — prefer loud failure over silent nulls
-- ============================================================================


-- ──────────────────────────────────────────────────────────────────────────
-- scans — one row per scan request
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scans (
    id                    TEXT PRIMARY KEY,       -- uuid4[:8]
    url                   TEXT NOT NULL,           -- what the user asked for
    domain                TEXT NOT NULL,           -- normalized domain for grouping
    status                TEXT NOT NULL CHECK (status IN ('queued','running','completed','error')),
    progress              INTEGER NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    step                  TEXT,                    -- human-readable current step
    result                JSONB,                   -- full scan result blob once completed
    error                 TEXT,                    -- error message if status = 'error'

    -- Requester fingerprint (all hashed, never raw)
    ip_hash               TEXT NOT NULL,
    ua_hash               TEXT,
    session_id            UUID,                    -- client-side cookie, for correlating repeated visits
    fingerprint_hash      TEXT,                    -- optional canvas/webgl hash from frontend

    -- Consent & verification
    consent_accepted      BOOLEAN NOT NULL DEFAULT FALSE,
    consent_version       TEXT NOT NULL,           -- which ToS text was shown
    verified              BOOLEAN NOT NULL DEFAULT FALSE,
    verification_method   TEXT CHECK (verification_method IN ('meta','file','dns') OR verification_method IS NULL),

    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at          TIMESTAMPTZ
);

COMMENT ON TABLE scans IS
    'One row per scan. Replaces the in-memory scans dict in api.py.';


-- ──────────────────────────────────────────────────────────────────────────
-- verification_tokens — short-lived tokens for ownership proofs
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS verification_tokens (
    token           TEXT PRIMARY KEY,              -- cryptographically random, ~32 bytes hex
    domain          TEXT NOT NULL,
    method          TEXT NOT NULL CHECK (method IN ('meta','file','dns')),
    ip_hash         TEXT NOT NULL,

    status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','verified','expired','failed')),
    attempts        INTEGER NOT NULL DEFAULT 0,    -- how many times we tried to verify

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,          -- +1h for pending, +30d for verified
    verified_at     TIMESTAMPTZ
);

COMMENT ON TABLE verification_tokens IS
    'Short-lived tokens. Successful verifications are copied into verified_domains with a longer TTL.';


-- ──────────────────────────────────────────────────────────────────────────
-- verified_domains — 30-day grant: "this ip_hash owns this domain"
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS verified_domains (
    id          BIGSERIAL PRIMARY KEY,
    domain      TEXT NOT NULL,
    ip_hash     TEXT NOT NULL,
    method      TEXT NOT NULL CHECK (method IN ('meta','file','dns')),

    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL,              -- typically +30 days

    UNIQUE (domain, ip_hash)
);

COMMENT ON TABLE verified_domains IS
    'Cache of verified (domain, requester) pairs. Lets owners re-scan without re-verifying every time.';


-- ──────────────────────────────────────────────────────────────────────────
-- audit_log — APPEND ONLY forensic trail
-- ──────────────────────────────────────────────────────────────────────────
-- Every user action that touches the scanner gets a row here. Used for:
--   * Responding to abuse reports ("who scanned this domain and when")
--   * Responding to legal requests ("give us all activity from this IP range")
--   * Detecting attack patterns (many scans from same fingerprint_hash across IPs)
--   * Proving good-faith compliance in case of legal challenge
--
-- UPDATE and DELETE are revoked in migration 004 (rls_policies.sql). Rows
-- with flagged=TRUE are preserved past the normal 90-day retention.
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
    id                BIGSERIAL PRIMARY KEY,
    event             TEXT NOT NULL CHECK (event IN (
        'scan_request',
        'scan_start',
        'scan_complete',
        'scan_error',
        'scan_blocked_ssrf',
        'scan_blocked_rate_limit',
        'scan_truncated_deadline',
        'verify_request',
        'verify_success',
        'verify_failure',
        'abuse_report_submitted',
        'abuse_block_applied'
    )),

    scan_id           TEXT,                        -- nullable: verify events have no scan_id
    domain            TEXT,                        -- nullable

    ip_hash           TEXT NOT NULL,
    ua_hash           TEXT,
    fingerprint_hash  TEXT,
    session_id        UUID,

    details           JSONB NOT NULL DEFAULT '{}',
    flagged           BOOLEAN NOT NULL DEFAULT FALSE,  -- set TRUE to exempt from pruning

    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE audit_log IS
    'Append-only forensic trail. UPDATE and DELETE are revoked by migration 004.';


-- ──────────────────────────────────────────────────────────────────────────
-- rate_limits — persistent replacement for in-memory _rate_store
-- ──────────────────────────────────────────────────────────────────────────
-- Key scheme:
--   "ip:<ip_hash>"          — per-IP scans in rolling window (default 5/30m)
--   "ip_targets:<ip_hash>"  — distinct target domains per IP (default 3/24h)
--   "domain:<domain>"       — per-domain scan count (anti-abuse)
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rate_limits (
    key              TEXT PRIMARY KEY,
    count            INTEGER NOT NULL DEFAULT 1,
    distinct_values  JSONB,                         -- for "ip_targets:*" keys, stores the set of seen domains
    window_start     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    window_seconds   INTEGER NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE rate_limits IS
    'Survives server restart. Replaces in-memory _rate_store in api.py.';


-- ──────────────────────────────────────────────────────────────────────────
-- abuse_reports — submitted by site owners who find their domain in scans
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS abuse_reports (
    id                  BIGSERIAL PRIMARY KEY,
    reported_domain     TEXT NOT NULL,
    reporter_email      TEXT,                      -- optional, hashed? raw for contact-back
    reporter_ip_hash    TEXT NOT NULL,
    description         TEXT,

    status              TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewed','dismissed','confirmed')),
    related_scan_ids    TEXT[],                    -- array of scan IDs the reporter references

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at         TIMESTAMPTZ,
    reviewer_notes      TEXT
);

COMMENT ON TABLE abuse_reports IS
    'Submitted via the /abuse-report endpoint. Triggers flagging of related audit_log rows.';

-- =====================================================================
-- === 003_indexes.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 003 — indexes on core tables
-- ============================================================================
-- Indexes are created AFTER the tables (separate migration) so schema
-- changes to the tables themselves stay clean and reviewable, and so
-- adding a new index later is a new migration file instead of an edit.
--
-- All indexes use IF NOT EXISTS for idempotency — the migration runner
-- is safe to re-run on a partially-applied state.
-- ============================================================================


-- ──────────────────────────────────────────────────────────────────────────
-- scans
-- ──────────────────────────────────────────────────────────────────────────
-- Lookups: "show me my recent scans" and "scan history for domain X"
CREATE INDEX IF NOT EXISTS idx_scans_ip_hash_created
    ON scans (ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scans_domain_created
    ON scans (domain, created_at DESC);

-- For polling active scan status
CREATE INDEX IF NOT EXISTS idx_scans_status
    ON scans (status)
    WHERE status IN ('queued','running');


-- ──────────────────────────────────────────────────────────────────────────
-- verification_tokens
-- ──────────────────────────────────────────────────────────────────────────
-- Cleanup job needs to find expired tokens
CREATE INDEX IF NOT EXISTS idx_verify_tokens_expires
    ON verification_tokens (expires_at)
    WHERE status = 'pending';

-- Lookup when user submits a verify check
CREATE INDEX IF NOT EXISTS idx_verify_tokens_domain_status
    ON verification_tokens (domain, status);


-- ──────────────────────────────────────────────────────────────────────────
-- verified_domains
-- ──────────────────────────────────────────────────────────────────────────
-- Hot path: "is this (domain, ip_hash) currently verified"
-- UNIQUE (domain, ip_hash) on the table already provides this, but we
-- also want expiry-aware lookups
CREATE INDEX IF NOT EXISTS idx_verified_domains_lookup
    ON verified_domains (domain, ip_hash, expires_at DESC);

-- Cleanup: find expired grants
CREATE INDEX IF NOT EXISTS idx_verified_domains_expires
    ON verified_domains (expires_at);


-- ──────────────────────────────────────────────────────────────────────────
-- audit_log — these are the critical forensic indexes
-- ──────────────────────────────────────────────────────────────────────────
-- "Who scanned this domain?"
CREATE INDEX IF NOT EXISTS idx_audit_domain_created
    ON audit_log (domain, created_at DESC)
    WHERE domain IS NOT NULL;

-- "What has this IP been up to?"
CREATE INDEX IF NOT EXISTS idx_audit_ip_hash_created
    ON audit_log (ip_hash, created_at DESC);

-- "Same device across different IPs" (fingerprint correlation)
CREATE INDEX IF NOT EXISTS idx_audit_fingerprint_created
    ON audit_log (fingerprint_hash, created_at DESC)
    WHERE fingerprint_hash IS NOT NULL;

-- Event-type filters for dashboards
CREATE INDEX IF NOT EXISTS idx_audit_event_created
    ON audit_log (event, created_at DESC);

-- Cleanup job: find unflagged rows older than retention window
CREATE INDEX IF NOT EXISTS idx_audit_prune
    ON audit_log (created_at)
    WHERE flagged = FALSE;


-- ──────────────────────────────────────────────────────────────────────────
-- rate_limits
-- ──────────────────────────────────────────────────────────────────────────
-- Cleanup job: find expired windows.
-- NOTE: We cannot put `window_start + interval_from_window_seconds` into an
-- expression index because all Postgres text-to-interval casts and the
-- make_interval() function are marked STABLE, not IMMUTABLE. So we index
-- plain window_start; the prune query still benefits (it scans oldest rows
-- first and re-evaluates the predicate per row — fine for a small hot table).
CREATE INDEX IF NOT EXISTS idx_rate_limits_window_start
    ON rate_limits (window_start);


-- ──────────────────────────────────────────────────────────────────────────
-- abuse_reports
-- ──────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_abuse_domain
    ON abuse_reports (reported_domain);

CREATE INDEX IF NOT EXISTS idx_abuse_status_created
    ON abuse_reports (status, created_at DESC);

-- =====================================================================
-- === 004_rls_policies.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 004 — Row-Level Security policies
-- ============================================================================
-- Supabase exposes tables over PostgREST with two built-in roles:
--   * anon          — what the public anon key sees
--   * authenticated — what a logged-in user sees (we don't use auth yet)
--   * service_role  — bypasses ALL RLS. Backend only.
--
-- Our rule: RLS is enabled on every table with NO policies for anon or
-- authenticated. That is a default-deny — the anon key sees nothing.
-- All application reads/writes go through the FastAPI backend using the
-- service_role key, which bypasses RLS.
--
-- Additionally, audit_log has UPDATE and DELETE revoked even for the
-- service_role. That table is append-only. If you ever need to rewrite
-- history, that's a conscious migration change, not a runtime operation.
-- ============================================================================


-- ──────────────────────────────────────────────────────────────────────────
-- Enable RLS on everything (default deny)
-- ──────────────────────────────────────────────────────────────────────────
ALTER TABLE scans                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_tokens    ENABLE ROW LEVEL SECURITY;
ALTER TABLE verified_domains       ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log              ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits            ENABLE ROW LEVEL SECURITY;
ALTER TABLE abuse_reports          ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_migrations      ENABLE ROW LEVEL SECURITY;


-- ──────────────────────────────────────────────────────────────────────────
-- Explicit denials for anon — no policies = no access, but we also
-- REVOKE to make the intent unambiguous and independent of RLS behaviour.
-- ──────────────────────────────────────────────────────────────────────────
REVOKE ALL ON scans                FROM anon, authenticated;
REVOKE ALL ON verification_tokens  FROM anon, authenticated;
REVOKE ALL ON verified_domains     FROM anon, authenticated;
REVOKE ALL ON audit_log            FROM anon, authenticated;
REVOKE ALL ON rate_limits          FROM anon, authenticated;
REVOKE ALL ON abuse_reports        FROM anon, authenticated;
REVOKE ALL ON schema_migrations    FROM anon, authenticated;


-- ──────────────────────────────────────────────────────────────────────────
-- audit_log is APPEND ONLY — even the service role cannot UPDATE or DELETE.
-- ──────────────────────────────────────────────────────────────────────────
-- This is enforced at the grant level, not via RLS, because RLS policies
-- can be added/removed at runtime but revokes require a migration.
REVOKE UPDATE, DELETE ON audit_log FROM service_role;

-- Only the prune job (run as a Supabase cron, see migration 005) should
-- be able to delete non-flagged rows past the retention window. Cron jobs
-- in Supabase run with superuser privileges, so they can bypass this.
-- Explicit note for future me:
--
--   To delete rows as part of retention, run the cleanup function defined
--   in migration 005 via cron. Do NOT grant DELETE back to service_role.

COMMENT ON TABLE audit_log IS
    'APPEND ONLY. UPDATE/DELETE revoked from service_role. Managed by pg_cron (see migration 005).';


-- ──────────────────────────────────────────────────────────────────────────
-- schema_migrations is also append-only (migrations never get un-applied
-- without a conscious manual intervention).
-- ──────────────────────────────────────────────────────────────────────────
REVOKE UPDATE, DELETE ON schema_migrations FROM service_role;

-- =====================================================================
-- === 005_cron_jobs.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 005 — scheduled maintenance via pg_cron
-- ============================================================================
-- Supabase enables the `pg_cron` extension on all tiers. We use it to:
--
--   1. Expire pending verification tokens that hit their deadline
--   2. Prune unflagged audit_log rows older than 90 days
--   3. Clean up expired verified_domains grants
--   4. Clean up stale rate_limits windows
--
-- These functions run with superuser privileges via pg_cron, so they
-- can bypass the REVOKE DELETE on audit_log that applies to service_role.
-- ============================================================================


-- Make sure the extension is enabled. Supabase projects have it by default
-- but it's safe to request it explicitly.
CREATE EXTENSION IF NOT EXISTS pg_cron;


-- ──────────────────────────────────────────────────────────────────────────
-- Function: expire pending verification tokens
-- ──────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION expire_pending_verification_tokens()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE verification_tokens
       SET status = 'expired'
     WHERE status = 'pending'
       AND expires_at < NOW();
END;
$$;


-- ──────────────────────────────────────────────────────────────────────────
-- Function: prune old unflagged audit_log rows (90-day retention)
-- ──────────────────────────────────────────────────────────────────────────
-- Flagged rows (linked to abuse reports or legal holds) are kept forever.
CREATE OR REPLACE FUNCTION prune_old_audit_log()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM audit_log
     WHERE created_at < NOW() - INTERVAL '90 days'
       AND flagged = FALSE;
END;
$$;


-- ──────────────────────────────────────────────────────────────────────────
-- Function: clean up expired verified_domains
-- ──────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION prune_expired_verified_domains()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM verified_domains
     WHERE expires_at < NOW();
END;
$$;


-- ──────────────────────────────────────────────────────────────────────────
-- Function: clean up stale rate_limits windows
-- ──────────────────────────────────────────────────────────────────────────
-- A rate limit row is stale when its window has fully elapsed and it
-- hasn't been updated since. We give a 2x buffer before deleting so
-- in-flight windows are never accidentally cleaned.
CREATE OR REPLACE FUNCTION prune_stale_rate_limits()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM rate_limits
     WHERE window_start + (window_seconds * 2 || ' seconds')::interval < NOW();
END;
$$;


-- ──────────────────────────────────────────────────────────────────────────
-- Schedule the jobs
-- ──────────────────────────────────────────────────────────────────────────
-- cron.schedule(job_name, schedule, sql) — idempotent via unschedule-before-schedule
-- so the migration can be re-run safely.

-- Token expiry — every 5 minutes
SELECT cron.unschedule('expire-verification-tokens')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'expire-verification-tokens');
SELECT cron.schedule(
    'expire-verification-tokens',
    '*/5 * * * *',
    $$SELECT expire_pending_verification_tokens();$$
);

-- Audit prune — once a day at 03:00 UTC
SELECT cron.unschedule('prune-audit-log')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'prune-audit-log');
SELECT cron.schedule(
    'prune-audit-log',
    '0 3 * * *',
    $$SELECT prune_old_audit_log();$$
);

-- Verified domains prune — once a day at 03:05 UTC
SELECT cron.unschedule('prune-verified-domains')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'prune-verified-domains');
SELECT cron.schedule(
    'prune-verified-domains',
    '5 3 * * *',
    $$SELECT prune_expired_verified_domains();$$
);

-- Rate limits prune — every hour
SELECT cron.unschedule('prune-rate-limits')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'prune-rate-limits');
SELECT cron.schedule(
    'prune-rate-limits',
    '0 * * * *',
    $$SELECT prune_stale_rate_limits();$$
);

-- =====================================================================
-- === 006_function_search_path_hardening.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 006 — harden search_path on all SECURITY DEFINER functions
-- ============================================================================
-- The functions defined in migration 005 run as SECURITY DEFINER, which
-- means they execute with the privileges of the function's owner (typically
-- postgres superuser) rather than the caller. That's necessary so pg_cron
-- can bypass the audit_log DELETE revoke from service_role.
--
-- But SECURITY DEFINER without an explicit search_path is a known attack
-- vector: an attacker with CREATE privileges on any schema in the resolver
-- path can shadow built-in operators or tables, and the function — running
-- with elevated rights — will use the attacker's objects.
--
-- Fix: pin search_path to `public, pg_temp` on every function. `pg_temp`
-- stays at the end so temporary tables still work, but nothing else from
-- an attacker-controlled schema can shadow our references.
--
-- Reference: https://supabase.com/docs/guides/database/database-linter?lint=0011_function_search_path_mutable
-- ============================================================================

ALTER FUNCTION public.expire_pending_verification_tokens() SET search_path = public, pg_temp;
ALTER FUNCTION public.prune_old_audit_log()               SET search_path = public, pg_temp;
ALTER FUNCTION public.prune_expired_verified_domains()    SET search_path = public, pg_temp;
ALTER FUNCTION public.prune_stale_rate_limits()           SET search_path = public, pg_temp;

-- =====================================================================
-- === 007_explicit_deny_policies.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 007 — explicit DENY-ALL policies for anon/authenticated
-- ============================================================================
-- Migration 004 enabled RLS on every table and REVOKEd all grants for the
-- anon/authenticated roles. That's already airtight (no grants = nothing
-- reaches the RLS layer), but Supabase's database linter flags tables with
-- RLS enabled and zero policies as `rls_enabled_no_policy` (INFO).
--
-- To make the default-deny explicit IN the schema — so anyone reading it
-- sees the intent, not just the grant state — we add `USING (false)`
-- policies for each table targeting the anon and authenticated roles.
--
-- service_role is NOT targeted: it bypasses RLS, and that's how the backend
-- gets in.
--
-- Reference: https://supabase.com/docs/guides/database/database-linter?lint=0008_rls_enabled_no_policy
-- ============================================================================

-- Helper pattern: one policy per table per role. Using FOR ALL covers
-- SELECT, INSERT, UPDATE, DELETE in a single definition.

-- scans
CREATE POLICY "deny_all_anon"          ON scans               FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON scans               FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- verification_tokens
CREATE POLICY "deny_all_anon"          ON verification_tokens FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON verification_tokens FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- verified_domains
CREATE POLICY "deny_all_anon"          ON verified_domains    FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON verified_domains    FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- audit_log
CREATE POLICY "deny_all_anon"          ON audit_log           FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON audit_log           FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- rate_limits
CREATE POLICY "deny_all_anon"          ON rate_limits         FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON rate_limits         FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- abuse_reports
CREATE POLICY "deny_all_anon"          ON abuse_reports       FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON abuse_reports       FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- schema_migrations
CREATE POLICY "deny_all_anon"          ON schema_migrations   FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON schema_migrations   FOR ALL TO authenticated USING (false) WITH CHECK (false);

-- =====================================================================
-- === 008_backup_infrastructure.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 008 — backup infrastructure
-- ============================================================================
-- Sets up the offsite backup system:
--
--   1. Enables `pg_net` so the database can call HTTP endpoints
--      (needed so pg_cron can trigger the backup edge function).
--
--   2. Creates `backup_log` — a small audit table that records each
--      backup attempt, its outcome, and the R2 object key. This is how
--      we'll know if backups stop working without needing to poll R2.
--
--   3. Creates `prune_old_backup_log()` so the log doesn't grow forever.
--
--   4. Schedules the daily cron job that calls the `backup` edge function.
--      The webhook auth secret is read from Supabase Vault at call time,
--      never embedded in this file (which lives in git).
--
-- Secrets this migration depends on existing in vault.secrets:
--   - backup_webhook_secret  (set separately via execute_sql, NOT in git)
--
-- Free tier note: pg_net is available on all Supabase tiers. Edge functions
-- have a 500k invocation/month free tier limit — we use 30 (one per day),
-- so we have ~4 orders of magnitude of headroom.
-- ============================================================================


-- ──────────────────────────────────────────────────────────────────────────
-- 1. Enable pg_net extension
-- ──────────────────────────────────────────────────────────────────────────
-- pg_net installs objects into the `net` schema.
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;


-- ──────────────────────────────────────────────────────────────────────────
-- 2. backup_log — record of every backup attempt
-- ──────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS backup_log (
    id               BIGSERIAL PRIMARY KEY,
    started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at     TIMESTAMPTZ,

    status           TEXT NOT NULL DEFAULT 'running'
                     CHECK (status IN ('running','success','error')),

    -- Outcome details
    r2_object_key    TEXT,                    -- e.g. "backups/2026/04/10/backup-20260410T040012Z.json.gz.enc"
    bytes_written    BIGINT,                  -- size of encrypted blob on R2
    rows_exported    JSONB,                   -- {"audit_log": 1234, "scans": 567, ...}
    error_message    TEXT,                    -- populated if status = 'error'

    -- Who kicked off the backup
    trigger_source   TEXT NOT NULL            -- 'cron' | 'manual' | 'test'
);

COMMENT ON TABLE backup_log IS
    'Audit trail of backup attempts. Populated by the backup edge function.';

CREATE INDEX IF NOT EXISTS idx_backup_log_started
    ON backup_log (started_at DESC);

CREATE INDEX IF NOT EXISTS idx_backup_log_status
    ON backup_log (status, started_at DESC)
    WHERE status != 'success';  -- partial index: cheap "show me failures"

-- Enable RLS + explicit deny (consistent with other tables)
ALTER TABLE backup_log ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON backup_log FROM anon, authenticated;

CREATE POLICY "deny_all_anon"          ON backup_log FOR ALL TO anon          USING (false) WITH CHECK (false);
CREATE POLICY "deny_all_authenticated" ON backup_log FOR ALL TO authenticated USING (false) WITH CHECK (false);


-- ──────────────────────────────────────────────────────────────────────────
-- 3. Prune function: keep last 180 days of backup_log (6 months)
-- ──────────────────────────────────────────────────────────────────────────
-- We keep successful backup records longer than we keep the actual R2
-- objects (which are pruned by R2 lifecycle rule at 90 days). That way
-- we still have a paper trail even after the blobs themselves are gone.
CREATE OR REPLACE FUNCTION prune_old_backup_log()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    DELETE FROM backup_log
     WHERE started_at < NOW() - INTERVAL '180 days';
END;
$$;


-- ──────────────────────────────────────────────────────────────────────────
-- 4. Schedule daily backup via pg_cron
-- ──────────────────────────────────────────────────────────────────────────
-- The cron job:
--   a) reads the webhook secret from Vault
--   b) calls the `backup` edge function via pg_net
--   c) the edge function does the actual export+encrypt+upload
--
-- We schedule at 04:00 UTC — 1 hour after `prune-audit-log` (03:00), so
-- the backup captures the post-prune state rather than a mix.

-- Unschedule first (idempotent re-runs)
SELECT cron.unschedule('daily-backup')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'daily-backup');

SELECT cron.schedule(
    'daily-backup',
    '0 4 * * *',
    $$
    SELECT net.http_post(
        url := 'https://wmerashfovgaugxpexqo.supabase.co/functions/v1/backup',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'X-Webhook-Secret', (
                SELECT decrypted_secret
                  FROM vault.decrypted_secrets
                 WHERE name = 'backup_webhook_secret'
            )
        ),
        body := jsonb_build_object('trigger', 'cron'),
        timeout_milliseconds := 60000
    );
    $$
);

-- Schedule the backup_log prune alongside the other prunes
SELECT cron.unschedule('prune-backup-log')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'prune-backup-log');
SELECT cron.schedule(
    'prune-backup-log',
    '10 3 * * *',   -- 03:10 UTC, chained after other prunes
    $$SELECT prune_old_backup_log();$$
);

-- =====================================================================
-- === 009_backup_secrets_rpc.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 009 — RPC wrapper for reading backup secrets from Vault
-- ============================================================================
-- The `backup` edge function needs to read 7 secrets from Supabase Vault:
--     r2_account_id, r2_access_key_id, r2_secret_access_key,
--     r2_bucket, r2_endpoint,
--     backup_encryption_key, backup_webhook_secret
--
-- Supabase's standard `vault.decrypted_secrets` view requires SELECT on the
-- `vault` schema, which is granted only to `postgres` by default — the
-- `service_role` that edge functions use cannot read it directly.
--
-- Rather than grant `service_role` access to the entire vault schema (which
-- would expose ALL secrets, not just backup ones), we expose a narrow
-- SECURITY DEFINER function that returns ONLY the backup-related secrets
-- as a single jsonb object. service_role gets EXECUTE on this one function
-- and nothing else.
--
-- The secrets themselves are stored in vault.secrets via a one-off
-- execute_sql call at bootstrap time (NOT in this migration — secrets
-- never go in git). If the secrets are missing, the function raises a
-- loud error rather than returning an empty object silently.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_backup_secrets()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp, vault
AS $$
DECLARE
    result jsonb;
BEGIN
    SELECT jsonb_object_agg(name, decrypted_secret)
      INTO result
      FROM vault.decrypted_secrets
     WHERE name IN (
         'r2_account_id',
         'r2_access_key_id',
         'r2_secret_access_key',
         'r2_bucket',
         'r2_endpoint',
         'backup_encryption_key',
         'backup_webhook_secret'
     );

    IF result IS NULL OR jsonb_typeof(result) <> 'object' THEN
        RAISE EXCEPTION 'backup secrets not found in vault';
    END IF;

    RETURN result;
END;
$$;

-- Lock down EXECUTE — only service_role can call this.
-- anon/authenticated must never see the secrets, even indirectly.
REVOKE ALL ON FUNCTION public.get_backup_secrets() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_backup_secrets() TO service_role;

-- =====================================================================
-- === 010_flag_audit_rows_rpc.sql ===
-- =====================================================================

-- ============================================================================
-- Migration 010 — RPC: flag_audit_rows_for_scan_ids
-- ============================================================================
-- audit_log has UPDATE and DELETE revoked from service_role (see migration
-- 004) because it's append-only by design. That's the right default — we
-- don't want the backend to be able to rewrite forensic history on a whim.
--
-- But there's exactly ONE legitimate UPDATE we need: when a user submits
-- an abuse report that cites specific scan IDs, we want to flag those
-- scans' audit_log rows so they're exempt from the daily 90-day prune
-- job (`prune_old_audit_log()`, see migration 005). Flagged rows become
-- legal evidence and must survive past the normal retention window.
--
-- We solve this by exposing a narrow SECURITY DEFINER function that:
--   - runs as the function's owner (postgres superuser), bypassing the
--     service_role grant restriction
--   - only permits the specific UPDATE we need (set flagged=TRUE)
--   - never sets flagged=FALSE — once flagged, always flagged (that's
--     the whole point of legal hold)
--   - takes an array of scan_ids as input so the caller can't pass
--     arbitrary SQL
--
-- Only service_role can EXECUTE this function. anon/authenticated can't
-- even see it. If the function itself leaks (via SQL injection somewhere
-- in application code), the blast radius is "attacker can flag additional
-- audit rows" — which extends retention, it doesn't hide anything.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.flag_audit_rows_for_scan_ids(p_scan_ids text[])
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    updated_count integer;
BEGIN
    -- Defensive: if the array is NULL or empty, return 0 without touching
    -- the table. plpgsql lets us return early cheaply.
    IF p_scan_ids IS NULL OR array_length(p_scan_ids, 1) IS NULL THEN
        RETURN 0;
    END IF;

    UPDATE audit_log
       SET flagged = TRUE
     WHERE scan_id = ANY(p_scan_ids)
       AND flagged = FALSE;

    GET DIAGNOSTICS updated_count = ROW_COUNT;
    RETURN updated_count;
END;
$$;

-- Lock down EXECUTE — only service_role can call this.
-- anon/authenticated never see it, so they can't flag rows
-- (which would inflate retention and waste space).
REVOKE ALL ON FUNCTION public.flag_audit_rows_for_scan_ids(text[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.flag_audit_rows_for_scan_ids(text[]) TO service_role;

COMMENT ON FUNCTION public.flag_audit_rows_for_scan_ids(text[]) IS
    'Flag audit_log rows to exempt them from 90-day pruning. Called when '
    'an abuse report cites specific scans that need legal-evidence retention. '
    'Only service_role can call; audit_log UPDATE is otherwise revoked.';
